### ISSUE TITLE
No contents in the Rscripts in the code folder

### ISSUE THREAD

**Issue by cxy-26** [qyxxx/info550_finalproject#1]

**Comment by qyxxx** [comment]
I'm sorry for the mistake. I have updated all the files, can I have my homework regraded?

**Comment by qyxxx** [comment]
It works well on my two laptops. I guess you may have some R packages uninstalled.

**Comment by cxy-26** [comment]
I've cloned the repository and run the make report.html again. The error still occurred.
<img width="550" alt="image" src="https://user-images.githubusercontent.com/98058400/199030505-3fee1fa5-96fd-4c31-b694-31cd6715fb41.png">
I think this is why the error occurred. There was not a directory called output in your repository.

**Comment by qyxxx** [comment]
My bad...I forgot to add a .gitkeep. It should work now.

**Comment by cxy-26** [comment]
It works. Great!

**Comment by qyxxx** [comment]
Thank you!

**Comment by benkeser** [comment]
love this thread.
