### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by benkeser** [qyxxx/info550_finalproject#3]
I am going to hold off on grading your final project, since it looks like there is an error in the Makefile. In particular, you need to make sure that the image is being tagged during `docker build` in the `<dockerhub_username>/<image_name>` style. Also when you use `docker run`, you need to make sure that the image is referenced using the `<dockerhub_username>/<image_name>` style.

**Comment by qyxxx** [comment]
Thank you for your response. I'm so sorry that I didn't read the instructions carefully. I supposed we want to build a local image in this project. I have updated the makefile and it works now (I tested the code in a windows machine with a docker pull and a make commend) Thanks!

**Comment by benkeser** [comment]
No it's my fault -- I should've made it more clear in the assignment/videos! Thanks for the corrections!
